### ISSUE TITLE
TypeError: Cannot read property 'time' of undefined

### ISSUE THREAD

**Issue by djjskzkzjz** [Nixes/mineflayer-bloodhound#3]
Trying to make a trip if the strike distance was more than three blocks. After any hit, the bot crashes
`/root/lc/node_modules/minecraft-protocol/src/transforms/framing.js:67
          } else { throw e }
                   ^

TypeError: Cannot read property 'time' of undefined
    at CorrelateAttack (/root/lc/node_modules/mineflayer-bloodhound/index.js:57:40)
    at CorrelateAttacks (/root/lc/node_modules/mineflayer-bloodhound/index.js:97:13)
    at Bot.<anonymous> (/root/lc/node_modules/mineflayer-bloodhound/index.js:106:9)
    at Bot.emit (events.js:310:20)
    at Client.<anonymous> (/root/lc/node_modules/mineflayer/lib/plugins/entities.js:304:24)
    at Client.emit (events.js:322:22)
    at FullPacketParser.<anonymous> (/root/lc/node_modules/minecraft-protocol/src/client.js:88:12)
    at FullPacketParser.emit (events.js:310:20)
    at addChunk (/root/lc/node_modules/readable-stream/lib/_stream_readable.js:298:12)
    at readableAddChunk (/root/lc/node_modules/readable-stream/lib/_stream_readable.js:280:11)
`

**Comment by Nixes** [comment]
Hmm, let me see if I can reproduce it. Thanks for the report.

**Comment by Nixes** [comment]
I can't reproduce it with my provided example code, I can attack with a bow from further than 3 blocks and not seeing any errors. Can you narrow the circumstances down a bit more?
