### ISSUE TITLE
TypeError: Cannot read property 'time' of undefined

### ISSUE THREAD

**Issue by djjskzkzjz** [Nixes/mineflayer-bloodhound#4]
I don't even understand why this is happening, the bot performs a function if someone hits it. Moreover, the error does not always appear, but somewhere in 1/15 of cases
Full error:
```
/root/mc/node_modules/minecraft-protocol/src/transforms/framing.js:67
          } else { throw e }
                   ^

TypeError: Cannot read property 'time' of undefined
    at CorrelateAttack (/root/mc/node_modules/mineflayer-bloodhound/index.js:68:40)
    at CorrelateAttacks (/root/mc/node_modules/mineflayer-bloodhound/index.js:108:13)
    at Bot.<anonymous> (/root/mc/node_modules/mineflayer-bloodhound/index.js:124:9)
    at Bot.emit (events.js:198:13)
    at Client.bot._client.on (/root/mc/node_modules/mineflayer/lib/plugins/entities.js:116:24)
    at Client.emit (events.js:198:13)
    at FullPacketParser.deserializer.on (/root/mc/node_modules/minecraft-protocol/src/client.js:89:12)
    at FullPacketParser.emit (events.js:198:13)
    at addChunk (/root/mc/node_modules/readable-stream/lib/_stream_readable.js:298:12)
    at readableAddChunk (/root/mc/node_modules/readable-stream/lib/_stream_readable.js:280:11)

```

Code:
```js
minecraft.on('onCorrelateAttack', function (attacker,victim) {
            if(victim.username == options.username){
                active_attack = true
                attackNearestPlayer()
            }
});

function attackNearestPlayer(){
    if(active_attack == true){
        if(Object.keys(minecraft.players).length == 1){
            console.log("Отсутствуют игроки")
            setTimeout(attackNearestPlayer,5000)
            return;
        }
        target = minecraft.nearestEntity(({ type }) => type === 'player')
        if(target == null){
            setTimeout(attackNearestPlayer,5000)
            return
        }
        let list = JSON.stringify(minecraft.players)
        if(list.includes(target.username) == false){
            console.log("Ищу нового игрока")
            setTimeout(attackNearestPlayer,5000)
            return
        }
        console.log(target.username + " является новой целью")
        minecraft.pathfinder.setMovements(defaultMove)
        minecraft.pathfinder.setGoal(new GoalFollow(target, 1), true)
        minecraft.setControlState('sprint', true)
        target_attack = setInterval(() => {
            minecraft.lookAt(target.position.offset(0, 1.6, 0),true, attack)   
            },300)
    }
} 
```

**Comment by Nixes** [comment]
Thanks for the example, I'll take a look when I have some time.

**Comment by DatArnoGuy** [comment]
This error seems to happen even when mineflayer-bloodhound is load but not used any way. I tested my bot with mineflayer-bloodhound plugin loaded but i didn't use it any way on my code (no event listening etc, only loading the plugin) and some times bot crashed with the same error. So i guess the problem is with creation of onCorrelateAttack-event.

**Comment by Connor-Johnson** [comment]
Try adding

```
  bot.on('death', () => {
    bot.pvp.stop()
    // If you use hawkeye uncomment // bot.hawkEye.stop()
  })

```
Worked for me :P

**Comment by Nixes** [comment]
Hmm this is a tough one, I had the example above running on a minecraft server with lots of spawned in zombies and skeletons initiating combat for 30 mins and still cannot see this issue once. Is it only when running for very long times that this appears? Or with specific minecraft versions? I just tested with MC 1.12.2, what have you folks been using?

**Comment by Nixes** [comment]
I have pushed a new 0.0.2 version of bloodhound that should fix this issue, please reopen if you still encounter it after updating.
